zen-browser/docs

- content/themes-store/themes-marketplace.md
On page https://docs.zen-browser.app/themes-store/themes-marketplace there is a link that leads to an old Themes store url (https://zenbrowser.io/themes).
This PR fixes it to the the correct url: https://www.zen-browser.app/themes
> docs: fix wrong url to the themes store

- content/faq.md
The links didn't have https:// at the beginning, so they led to a non-existent local file
> Fix links in faq

- content/guides/generic-optimized.md
When downloading Zen, most users will wonder what's the difference between the optimized and generic build.
The previous version of this topic had that information at the end, which causes users to miss the information.
I restructured this topic to have that information in a more prominent location. I also simplified the list as having listed every single supported family is not that helpful (most people will have issues locating their CPUs in such a long list)
> Re-organize the guide about optimized and generic builds

- content/contribute/desktop.md
The updated desktop repos read me added the following
```
In order to download and run zen locally, please follow [these instructions](https://docs.zen-browser.app/contribute/desktop).
```
But the linked document didn't explain how to run the browser locally, so I took the old instructions from the readme and added it here.
> Update contribute/desktop.md with instructions for running the browser locally

- content/guides/1password.md
Shortened a line in the "Guides" section of the sidebar to prevent overflow and ensure consistency with the layout.
> Fixed typo and shortened to 1 line

- content/guides/downloads.md
Some time ago (it seems at least from `1.0.2-b.3` as seen in zen-browser/desktop#3934), changes were made to the produced binaries and the download hub in the docs no longer reflected them accurately. We also recently stopped producing distinct optimized and generic builds.
This change attempts to make the download page up to date again :)
> Update downloads.md to reflect recent changes

- content/faq.md
Inside third step of split-view feature a link emoji (🔗) is used for button to access split view options:
But currently, a different icon is used for this purpose:
This PR replaces 🔗 emoji with `[|]` symbol
> docs(split-view): Change misleading split-view icon

- content/guides/1password.md
Custom browser support no longer requires a Labs feature:
The instructions are otherwise still accurate.
> Update "1Password Integration Fix" macOS instructions

- content/themes-store/themes-marketplace-submission-guidelines.md
The Docs said the image for a new mod has to be 300x200, but it actually seems to be 600x400 
(It worked for me with 600x400)
> themes-marketplace-submission-guidelines Image size to 600x400

- content/building.md
followup from https://github.com/zen-browser/desktop/pull/6507#issuecomment-2728374130, we should be using npm, not pnpm for building the repo.
> fix: use npm instead of pnpm

- content/building.md
When following the current documentation for building the desktop, I encountered the following error:
```
Unknown command: "build"
Did you mean this?
npm run build # run the "build" package script
To see a list of supported npm commands, run:
npm help
```
This PR updates the documentation to use `npm run build` instead of `npm build`, ensuring that the instructions work as expected.
> Update build command from `npm build` to `npm run build`

- content/building.md
While going through `building.md`, I noticed that some prerequisites weren’t mentioned, like explicitly Python 3, 7-Zip, and the `MOZILLABUILD` environment variable. Missing these causes build failures and confusing errors that are hard to debug.  
I’ve added these missing prerequisites to the documentation. I also created a new section, "Common Build Errors & Fixes," with solutions to issues I ran into during the build process.  
Let me know if any changes are needed!
> Added missing requirements for Zen Desktop build and added a new section for common fixes

- content/docs/themes-store/themes-marketplace.mdx
Updated the link to the Submission Guidelines page to use a relative path. This ensures proper navigation and prevents potential linking issues.
Fixes ##175
> Fix broken link in themes marketplace submission guidelines

- content/docs/themes-store/themes-marketplace.mdx
remove file extension because right now it's leads to empty page
https://docs.zen-browser.app/themes-store/themes-store/themes-marketplace-submission-guidelines.md
> Fix link in themes-marketplace.mdx

- content/docs/user-manual/urlbar.mdx
Screenshots and GIF/video to insert (already prepared by Shadow):
- Search Engine selection in onboarding screen (set zen.welcome-screen.seen to false to reenable onboarding screen again),
- SS of right click context menu when rightclicking URL bar on youtube.com (demonstrating adding website as search engine),
- List of search engines in Settings > Search > Search Shortcuts (preferably with some custom website added like yt/spotify/github),
- A gif of using custom search engine keyword in URL bar, like using YouTube with steps listed above, 
- example of adding a custom search engine manually (perhaps using Qwant? or SearXNG?)
> Enhance the "Zen URL bar" article into "URL Bar & Search Functions"

- content/docs/guides/about-config-flags.mdx
- content/docs/guides/about:config-flags.mdx
Referring to [this issue](https://github.com/zen-browser/docs/issues/187). I mostly wrote about non-debug about:config flags that aren't also in about:preferences. Currently this PR has two unfinished entries: `zen.view.experimental-rounded-view` and `zen.view.sidebar-height-throttle`, since I'm not sure what these do and didn't find enough info about them online.
Feel free to tell me if I need to add something, change my wording in certain places, or if this page should be somewhere else entirely.
> added a list of relevant about:config flags to the Guides section

- components/KeyboardShortcut.tsx
- content/docs/contribute/docs/editing-with-vscode.mdx
- content/docs/faq.mdx
- content/docs/guides/live-editing.mdx
- content/docs/themes-store/themes-marketplace-preferences.mdx
- content/docs/user-manual/bookmarks.mdx
- content/docs/user-manual/compact-mode.mdx
- content/docs/user-manual/extensions.mdx
- content/docs/user-manual/glance.mdx
- content/docs/user-manual/pip.mdx
- content/docs/user-manual/split-view.mdx
- content/docs/user-manual/urlbar.mdx
- tsconfig.json
https://zen-docs-nine.vercel.app/user-manual/pip
> Added KeyboardShortcut component for consistent key display

- content/docs/guides/about-config-flags.mdx
Updated the advanced preferences documentation to include the new zen.glance.enable-contextmenu-search setting.
> Add documentation for zen.glance.enable-contextmenu-search preference

- content/docs/contribute/www.mdx
As we are using `pnpm` for `www` repository, so I have updated the contribution guide.
> docs(www): switch contribution guide to pnpm

- content/docs/contribute/contributing.mdx
- content/docs/contribute/desktop.mdx
- content/docs/index.mdx
- src/app/guides/building/page.tsx
Hi there,
I found the current documentation structure is kinda confusing. As a web browser developer, I naturally navigated to the Developer section when looking for build instructions:
However, the building guideline is apparently not in here:
Eventually, I discovered the Building Guidelines are located under **Getting Started** — a section I thought was intended for general users wanting to explore the browser, rather than developers looking to build it from source 😂:
Although the homepage does include an entry point to the guide, I feel [several developers](https://github.com/zen-browser/desktop/issues/8723) have still overlooked it so they opened the issue on the GitHub...
Given that, this PR is to help developers find the building guidelines easily (and with a minimal redirect …
> chore: move Zen Browser guidelines to developers section

- content/docs/guides/live-editing.mdx
> Added missing step for live editing configuration

- content/docs/contribute/desktop/index.mdx
> docs(contribute): fix desktop contribution guide card
